import {mkdirSync,writeFileSync,readFileSync,readdirSync,copyFileSync} from 'node:fs';
import {activities,categories,foods,locales,validate} from './validate-data.js';
import {calories} from '../src/calculator.js';
import {siteConfig} from './site-config.js';
validate();
const {origin,indexable}=siteConfig();
const esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const tpl=readFileSync('templates/base.html','utf8');
const paths=[];
function write(path,content){mkdirSync('dist/'+path.substring(0,path.lastIndexOf('/')+1),{recursive:true});writeFileSync('dist/'+path,content)}
const icon=a=>categories.find(c=>c.id===a.category).icon;
for(const l of locales){
 const t=k=>esc(l[k]);
 const href=a=>`/${l.lang}/${a.slug}/`;
 const name=a=>esc(l.activities[a.id].name);
 const card=a=>`<a class="activity-card" data-search="${esc(l.activities[a.id].name+' '+l.activities[a.id].description+' '+l.categories[a.category])}" data-category="${a.category}" href="${href(a)}"><span class="activity-icon ${a.category}">${icon(a)}</span><div><small>${esc(l.categories[a.category])}</small><h3>${name(a)}</h3><p>${esc(l.activities[a.id].description)}</p></div><span class="card-bottom"><b>${a.met.toFixed(1)} <small>MET</small></b><span>↗</span></span></a>`;
 const info=`<section id="about" class="info-grid"><div><span class="eyebrow">THE SCIENCE</span><h2>${t('metTitle')}</h2><p>${t('metText')}</p></div><div><h3>${t('formula')}</h3><code>kcal = MET × 3.5 × kg ÷ 200 × min</code><p>${t('note')}</p><a href="https://pacompendium.com/adult-compendium/" target="_blank" rel="noopener">${t('source')} ↗</a></div></section>`;
 function calc(a,locked=false){return `<section class="calculator panel" id="calculator"><div class="calc-input"><span class="eyebrow">ENERGY CALCULATOR</span><h2>${t('quick')}</h2><p>${t('quickSub')}</p><label>${t('activity')}<select id="activity" ${locked?'disabled':''}>${activities.map(x=>`<option value="${x.id}" ${x.id===a.id?'selected':''}>${name(x)} · ${x.met} MET</option>`).join('')}</select></label><div class="input-pair"><label>${t('weight')}<span class="input-unit"><input id="weight" type="number" min="1" max="500" step="0.1" value="70" inputmode="decimal"><span>kg</span></span></label><label>${t('minutes')}<span class="input-unit"><input id="minutes" type="number" min="0" max="1440" step="1" value="30" inputmode="decimal"><span>${t('min')}</span></span></label></div><div class="presets">${[15,30,60,90].map(n=>`<button type="button" data-minutes="${n}" aria-pressed="${n===30}">${n} ${t('min')}</button>`).join('')}</div><p class="error" id="error" role="alert" hidden>${t('invalid')}</p><small class="live">● ${t('live')}</small></div><div class="calc-result"><span class="result-label">${t('result')}</span><div class="result-number"><output id="result" aria-live="polite">${Math.round(calories(a.met,70,30))}</output><span>kcal</span></div><p id="result-context">${name(a)} · 70 kg · 30 ${t('min')}</p><span class="result-rule"></span><small>${t('estimate')}</small><a id="detail-link" href="${href(a)}">${t('detail')} <span>↗</span></a></div></section>`}
 function comparison(a){return `<section class="panel section-pad"><div class="section-heading"><h2>${t('compare')}</h2><span class="context" data-context></span></div><div id="comparison">${activities.slice(0,5).map(x=>`<div class="bar-row"><a href="${href(x)}">${name(x)}</a><div class="bar-track"><div style="width:${x.met/8.5*100}%"></div></div><b>${Math.round(calories(x.met,70,30))} <small>kcal</small></b></div>`).join('')}</div></section>`}
 function extras(a){return `<div class="tables"><section class="panel section-pad"><h2>${t('timeTable')}</h2><p data-weight-context>70 kg</p><table><thead><tr><th>${t('minutes')}</th><th>kcal</th></tr></thead><tbody id="time-table">${[10,20,30,45,60,90,120].map(n=>`<tr><td>${n} ${t('min')}</td><td>${Math.round(calories(a.met,70,n))}</td></tr>`).join('')}</tbody></table></section><section class="panel section-pad"><h2>${t('weightTable')}</h2><p data-time-context>30 ${t('min')}</p><table><thead><tr><th>${t('weight')}</th><th>kcal</th></tr></thead><tbody id="weight-table">${[40,50,60,70,80,90,100].map(n=>`<tr><td>${n} kg</td><td>${Math.round(calories(a.met,n,30))}</td></tr>`).join('')}</tbody></table></section></div>${comparison(a)}<section class="food-section"><span class="eyebrow">A FAMILIAR PERSPECTIVE</span><h2>${t('food')}</h2><div class="food-grid">${foods.map(f=>`<div class="food-card"><span>${f.icon}</span><div><h3>${esc(l.foods[f.id])}</h3><strong data-food="${f.id}">${(calories(a.met,70,30)/f.kcal).toFixed(1)}</strong> ×</div></div>`).join('')}</div><p class="muted">${t('foodNote')}</p></section>`}
 function reverse(){return `<section class="panel section-pad" id="reverse"><div class="section-heading"><div><span class="eyebrow">YOUR ENERGY GOAL</span><h2>${t('reverse')}</h2></div><label>${t('target')}<span class="input-unit"><input id="target" type="number" value="500" min="0" max="100000" step="1"><span>kcal</span></span></label></div><button class="text-button" id="fat" type="button">${t('fat')} ↗</button><p>${t('fatNote')}</p><div id="reverse-results" class="reverse-grid"></div></section>`}
 function render(path,title,description,content,a,category){
  paths.push(path);
  const suffix=path.split('/').slice(2).join('/');
  const langs=locales.map(x=>`<a href="/${x.lang}/${suffix}" lang="${x.lang}" ${x.lang===l.lang?'aria-current="page"':''}>${esc(x.nativeName)}</a>`).join('');
  const seo=`<link rel="canonical" href="${origin}${path}">${locales.map(x=>`<link rel="alternate" hreflang="${x.lang}" href="${origin}/${x.lang}/${suffix}">`).join('')}<link rel="alternate" hreflang="x-default" href="${origin}/ja/${suffix}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:type" content="website"><meta property="og:url" content="${origin}${path}"><meta property="og:site_name" content="metdays">${indexable?'':'<meta name="robots" content="noindex,nofollow">'}`;
  const header=`<header><a class="brand" href="/${l.lang}/"><span class="brand-icon">m</span> met<span class="brand-light">days</span><span class="brand-dot">.</span></a><nav aria-label="${t('browse')}"><a href="/${l.lang}/#explore">${t('browse')}</a><a href="/${l.lang}/calculator/burn-500-calories/">${t('calculator')}</a><a href="#about">${t('about')}</a></nav><div class="languages">${langs}</div></header>`;
  const data=JSON.stringify({activities,categories,foods,locale:l,selected:a?.id||activities[0].id,category:category||null}).replaceAll('<','\\u003c');
  const values={lang:l.lang,title:esc(title),description:esc(description),seo,header,content:`<noscript><p class="notice">${t('nojs')}</p></noscript>${content}`,footer:t('footer'),data};
  write(path.slice(1)+'index.html',tpl.replace(/\{\{(\w+)\}\}/g,(_,k)=>values[k]??''));
 }
 const explorer=(category)=>`<section id="explore"><div class="section-heading"><div><span class="eyebrow">ACTIVITY LIBRARY</span><h2>${category?esc(l.categories[category]):t('explore')}</h2><p>${t('exploreSub')}</p></div><span class="count" id="count">${(category?activities.filter(a=>a.category===category):activities).length} ${t('count')}</span></div><label class="search-box"><span aria-hidden="true">⌕</span><input type="search" id="search" placeholder="${t('search')}" aria-label="${t('search')}"><span>↵</span></label><div class="filters"><button data-filter="all" aria-pressed="true">${t('all')}</button>${categories.map(c=>`<button data-filter="${c.id}" aria-pressed="false">${c.icon} ${esc(l.categories[c.id])}</button>`).join('')}</div><div class="activity-grid">${activities.filter(a=>!category||a.category===category).map(card).join('')}</div><p id="empty" hidden>${t('empty')}</p><div class="category-links">${categories.map(c=>`<a href="/${l.lang}/category/${c.id}/">${esc(l.categories[c.id])} ↗</a>`).join('')}</div></section>`;
 const hero=`<section class="hero"><div><span class="pill"><span>●</span> ${t('based')}</span><h1>${t('hero').replaceAll('\n','<br>')}</h1><p>${t('intro').replaceAll('\n','<br>')}</p><a class="primary-button" href="#explore">${t('browse')} <span>↗</span></a></div><div class="hero-art" aria-hidden="true"><div class="orbit orbit-one"></div><div class="orbit orbit-two"></div><span class="art-label">MOVE A LITTLE. FEEL A LOT.</span><svg viewBox="0 0 360 310"><path d="M35 270Q150 170 318 265" fill="none" stroke="#c7d1aa" stroke-width="2" stroke-dasharray="4 7"/><circle cx="211" cy="62" r="22" fill="#edb79c"/><path d="M190 88q-31 8-49 63l53 20 35-57z" fill="#2b5d4e"/><path d="m183 159-31 50-57 33m97-80 23 49 59 13" stroke="#283e36" stroke-width="22" fill="none" stroke-linecap="round"/><path d="m169 107-43 26-26-27m111 2 27 29 31-11" stroke="#edb79c" stroke-width="13" fill="none" stroke-linecap="round"/><path d="m83 245 17 8m173-29 15 8" stroke="#f3f0d9" stroke-width="14" stroke-linecap="round"/><path d="M191 56q5-34 36-13l4 17-27-8z" fill="#293e36"/></svg><div class="floating-met"><span>↗</span><div><strong>3.8 <small>MET</small></strong><small>${name(activities[0])}</small></div></div><div class="art-spark">✳</div></div></section>`;
 render(`/${l.lang}/`,'metdays — '+l.tagline,l.intro,hero+calc(activities[0])+explorer()+info);
 for(const c of categories)render(`/${l.lang}/category/${c.id}/`,l.categories[c.id]+' · metdays',l.exploreSub,`<div class="page-intro"><a href="/${l.lang}/">${t('home')} /</a><h1>${esc(l.categories[c.id])}</h1></div>`+explorer(c.id)+info,null,c.id);
 for(const a of activities)render(href(a),l.activities[a.id].name+l.titleSuffix+' | metdays',l.activities[a.id].description,`<section class="page-intro"><a href="/${l.lang}/">${t('home')}</a> / <a href="/${l.lang}/category/${a.category}/">${esc(l.categories[a.category])}</a><h1>${name(a)}${t('titleSuffix')}</h1><p>${esc(l.activities[a.id].description)}</p><span class="pill">${a.met} MET</span> <a class="source-link" href="${a.source_url}">${t('source')}: 2024 · ${a.source_code} ↗</a></section>`+calc(a,true)+extras(a)+reverse()+`<section><h2>${t('related')}</h2><div class="activity-grid">${activities.filter(x=>x.id!==a.id).sort((x,y)=>Number(y.category===a.category)-Number(x.category===a.category)).slice(0,4).map(card).join('')}</div></section>`+info,a);
 render(`/${l.lang}/calculator/burn-500-calories/`,l.reverse+' | metdays',l.fatNote,`<div class="page-intro"><h1>${t('reverse')}</h1></div>`+calc(activities[0])+reverse()+comparison(activities[0])+info);
}
write('index.html','<!doctype html><html lang="ja"><meta charset="utf-8"><meta http-equiv="refresh" content="0;url=/ja/"><title>metdays</title><a href="/ja/">日本語</a> <a href="/en/">English</a> <a href="/th/">ไทย</a></html>');
write('404.html','<!doctype html><html lang="en"><meta charset="utf-8"><title>404 · metdays</title><h1>404</h1><a href="/">metdays — Home</a></html>');
write('sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${paths.map(p=>`<url><loc>${esc(origin+p)}</loc></url>`).join('')}</urlset>`);
write('robots.txt',indexable?`User-agent: *\nAllow: /\nSitemap: ${origin}/sitemap.xml\n`:'User-agent: *\nDisallow: /\n');
write('_headers','/*\n  X-Content-Type-Options: nosniff\n  Referrer-Policy: strict-origin-when-cross-origin\n');
// Explicit traversal avoids a Windows Node 22 native cpSync crash on Japanese paths.
function copyDirectory(source, destination) {
  mkdirSync(destination, {recursive:true});
  for (const entry of readdirSync(source, {withFileTypes:true})) {
    const from = source + '/' + entry.name;
    const to = destination + '/' + entry.name;
    if (entry.isDirectory()) copyDirectory(from, to);
    else if (entry.isFile()) copyFileSync(from, to);
    else throw new Error('Unsupported asset type: ' + from);
  }
}
copyDirectory('assets','dist/assets');copyDirectory('src','dist/src');copyDirectory('data','dist/data');
console.log(`Built ${paths.length} pages in dist. Canonical origin: ${origin}`);

